# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a49780ac58f58052238a81a887e62bcbe5fa4a6051e4dd875876c7d45349f3b0c3ec7c5ae2d19a98f8da578e8d1e95efeeb7d7f1854da11b88953b9595d846c

test:
  secret_key_base: a7caec55de49d9e0e94c3de60a7a667077019c109247a060b354f5b8fed11e14137373d2adcc4106b70475179c79c1f343530a60043c34926550a6b6b702fe88

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
